# local machine settings (change according to your system)

DEPEND = g++
CC = g++ -Wall 
RELEASE_FLAGS = -O3 -DNDEBUG -std=gnu++11
DEBUG_FLAGS = -g -std=gnu++11
LINK = g++
LINK_LIBS = -lm
LINK_LIBS_V = -lm
#GL_FLAGS = -lm -lobjc -framework OpenGL -framework GLUT # for the Mac
GL_FLAGS = -fopenmp -lm -lGL -lGLU -lglut # for linux
